[package]
name = "growthbook-sdk-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
derive-new = "0.5.9"
getset = "0.1.2"
url = "2.4.0"
data-encoding = "2.4.0"
openssl = "0.10.54"
