name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build-and-test:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, wasm32-unknown-unknown]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy
      - name: Format Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check --verbose
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose -- -D warnings        
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
