name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
      - name: Format Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check --verbose
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose -- -D warnings     
      - name: Build x86_64-unknown-linux-gnu
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --target x86_64-unknown-linux-gnu
      - name: Build wasm32-unknown-unknown
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --no-default-features --target wasm32-unknown-unknown
      - name: Default Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
      - name: No-Default Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --verbose